const teamdata = [
  {
    id: 1,
    img: "https://lh3.googleusercontent.com/uwIxecgvOpwoX_c9JldhxuVOhTE2oZ8YEg6cRHQDULvQy4smqcC74Mpblk_z1F53Qpk=w2400",
    name: "Aditi Farkya",
    designation: "MTS at Salesforce",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 2,
    img: "https://lh5.googleusercontent.com/ktFB4E4cAKTnwwttHteTNh7k3JncNveZlp7ey7ppuzsAnbM0ZudRIxrclSl96VA9PVs=w2400",
    name: "Palabh Borah",
    designation: "SDE at Akamai Technologies",
    linkedinurl: "https://www.linkedin.com/in/pallav-borah-076320108/",
    githuburl: "https://github.com/Bhallora",
  },
  {
    id: 3,
    img: "https://drive.google.com/uc?export=view&id=1sfMYnY6cVsF8PuITK8V_2rsqhc9Zs3h0",
    name: "Divya Gavandi",
    designation: "SDE at ICICI Lombard GIC",
    linkedinurl: "http://www.linkedin.com/in/divya-gavandi",
    githuburl: "https://github.com/gavandivya",
  },
  {
    id: 4,
    img: "https://lh6.googleusercontent.com/L22We8LZSX0ItenMRianOxdkLPNyLiD8231HCYd5xWUSENNg_wMmozjwoeuw0630uy8=w2400",
    name: "Abhishek Sharma",
    designation: "Student at Glbitm",
    linkedinurl: "https://www.linkedin.com/in/abhishek-sharma-73b7811a0/",
    githuburl: "https://github.com/it-abhishek2000",
  },
  {
    id: 5,
    img: "https://drive.google.com/uc?export=view&id=1QaO6elNUIA1yUCMvgPU3_wAKwwE2QAlx",
    name: "Prajwal",
    designation: "SDE at EY",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 6,
    img: "https://lh5.googleusercontent.com/I80xqSyR2DchUodj_gxoXA13pH6-bf9A_VDpCLpZM0MzDtKAzRizSjeNXhveF8Urbn0=w2400",
    name: "Nikita Jit",
    designation: "SDE at Accenture",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 7,
    img: "https://lh3.googleusercontent.com/cPo1RiC81rAhahPMptGzFShtIw4rDaG5LwIRlMd0_pmrqSm59mDMgv-Uet5_shG0jBE=w2400",
    name: "Soumya",
    designation: "SDE at LTI",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 8,
    img: "https://lh3.googleusercontent.com/mPpXsAFU6m5DbQdea1tQ5YUNc9NxPS4VndZHfoSzmCU9ypy1mBvynOOidUPhml0NUNM=w2400",
    name: "Shreeraj",
    designation: "SDE at Bacancy Technology",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 9,
    img: "https://lh6.googleusercontent.com/vt4BHzkPbTmvg-RAoREZ-VJ3LAvZQ2CXeulVdilmIw3Xjn7T-bupa2XyGYf0_Htshdc=w2400",
    name: "Deepak Dev",
    designation: "SDE at Magic edtech",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
  {
    id: 10,
    img: "https://lh4.googleusercontent.com/lva0t8N0yvQCBnEG2EAve2BrUZXnI5Fr3BbtiZTvoNGjTzkYDepMn98Hs4nbRosBN_Y=w2400",
    name: "Anurag Ambekar",
    designation: "SDE at Born Group",
    linkedinurl: "https://www.linkedin.com/in/aditi-farkya-8b69b0a4/",
    githuburl: "https://github.com/aditifarkya",
  },
];
export default teamdata;
